# Generated by Django 4.0.4 on 2022-07-01 18:50

from django.db import migrations, models
import profiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='picture',
            field=models.ImageField(default='defaults/blog_default.webp', upload_to='banners/blogs', validators=[profiles.models.validate_image], verbose_name='banner'),
        ),
    ]
