# Generated by Django 4.0.4 on 2022-07-01 18:56

from django.db import migrations, models
import profiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(default='defaults/user_default.webp', upload_to='users/profiles', validators=[profiles.models.validate_image], verbose_name='picture'),
        ),
    ]
