# Generated by Django 4.0.4 on 2022-07-02 09:35

from django.db import migrations, models
import globals.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Global',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('company_name', models.CharField(max_length=100, unique=True, verbose_name='Company Name')),
                ('show_name', models.BooleanField(default=False, verbose_name='show name on navbar')),
                ('show_logo', models.BooleanField(default=True, verbose_name='show logo on navbar')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('address', models.TextField(verbose_name='address')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('contact_numbers', models.CharField(blank=True, max_length=100, verbose_name='contact_numbers')),
                ('logo', models.ImageField(blank=True, default='defaults/logo.png', upload_to='logos', validators=[globals.models.validate_image], verbose_name='logo')),
                ('google_analytics_tag', models.TextField(blank=True, verbose_name='google_analytics_tag')),
                ('additional_tags', models.TextField(blank=True, verbose_name='additional_tags')),
                ('privacy_policy', models.TextField(blank=True, verbose_name='privacy policy')),
                ('terms_of_service', models.TextField(blank=True, verbose_name='terms of service')),
            ],
        ),
    ]
