# Generated by Django 4.0.4 on 2022-07-02 09:40

from django.db import migrations, models
import globals.models


class Migration(migrations.Migration):

    dependencies = [
        ('globals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='global',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos', validators=[globals.models.validate_image], verbose_name='logo'),
        ),
    ]
