# Generated by Django 4.0.4 on 2022-12-13 15:56

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('globals', '0002_alter_global_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='global',
            name='security',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='security'),
        ),
        migrations.AlterField(
            model_name='global',
            name='privacy_policy',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='privacy policy'),
        ),
        migrations.AlterField(
            model_name='global',
            name='terms_of_service',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='terms of service'),
        ),
    ]
