# Generated by Django 4.0.4 on 2023-02-23 16:46

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import releasenote.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReleaseYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', releasenote.models.YearField()),
            ],
        ),
        migrations.CreateModel(
            name='ReleaseNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Release Note Title')),
                ('body', ckeditor.fields.RichTextField()),
                ('month', models.CharField(choices=[('january', 'January'), ('february', 'February'), ('march', 'March'), ('april', 'April'), ('may', 'May'), ('june', 'June'), ('july', 'July'), ('august', 'August'), ('september', 'September'), ('october', 'October'), ('november', 'November')], max_length=50, verbose_name='Release Month')),
                ('version', models.FloatField(verbose_name='Release Version')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='releasenote.releaseyear', verbose_name='Release Year')),
            ],
        ),
    ]
