# Generated by Django 4.0.4 on 2023-02-23 16:57

from django.db import migrations, models
import releasenote.models


class Migration(migrations.Migration):

    dependencies = [
        ('releasenote', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='releasenote',
            name='month',
            field=models.CharField(choices=[('january', 'January'), ('february', 'February'), ('march', 'March'), ('april', 'April'), ('may', 'May'), ('june', 'June'), ('july', 'July'), ('august', 'August'), ('september', 'September'), ('october', 'October'), ('november', 'November'), ('december', 'December')], max_length=50, verbose_name='Release Month'),
        ),
        migrations.AlterField(
            model_name='releaseyear',
            name='year',
            field=releasenote.models.YearField(unique=True),
        ),
    ]
