# Generated by Django 4.0.4 on 2023-02-23 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('releasenote', '0002_alter_releasenote_month_alter_releaseyear_year'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='releasenote',
            options={'get_latest_by': 'version'},
        ),
        migrations.AlterField(
            model_name='releasenote',
            name='version',
            field=models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Release Version'),
        ),
    ]
