# Generated by Django 4.0.4 on 2023-02-23 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('releasenote', '0003_alter_releasenote_options_alter_releasenote_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='releasenote',
            name='version',
            field=models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Release Version'),
        ),
    ]
