# Generated by Django 4.0.4 on 2023-02-24 05:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('releasenote', '0004_alter_releasenote_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='releasenote',
            name='unique_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='releasenote',
            name='version',
            field=models.CharField(max_length=50, verbose_name='Release Version'),
        ),
    ]
