# Generated by Django 4.0.4 on 2023-02-24 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('releasenote', '0005_releasenote_unique_id_alter_releasenote_version'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='releasenote',
            options={},
        ),
        migrations.AlterField(
            model_name='releasenote',
            name='version',
            field=models.CharField(max_length=50, unique=True, verbose_name='Release Version'),
        ),
    ]
