# Generated by Django 4.0.4 on 2022-07-01 11:40

import blogs.models
import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_alter_article_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='banner',
            field=models.ImageField(default='defaults/blog_default.webp', upload_to='banners/blogs', validators=[blogs.models.validate_image], verbose_name='banner'),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='Content'),
        ),
    ]
