# Generated by Django 4.0.4 on 2022-07-02 07:59

import blogs.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_alter_article_banner_alter_article_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('slug', models.SlugField(blank=True, null=True, verbose_name='slug')),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='banner',
            field=models.ImageField(default='defaults/blog_default.webp', upload_to='banners/blogs', validators=[blogs.models.validate_image], verbose_name='Banner'),
        ),
    ]
