# Generated by Django 4.0.4 on 2022-07-02 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_tag_alter_article_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, to='blogs.tag', verbose_name='Tags'),
        ),
    ]
