# Generated by Django 4.0.4 on 2024-08-05 07:30

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0007_tag_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('description', models.CharField(max_length=160, null=True, verbose_name='Short Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('slug', models.SlugField(blank=True, null=True, verbose_name='slug')),
            ],
        ),
        migrations.CreateModel(
            name='MetaTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField(blank=True, null=True, verbose_name='Relative URL')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta Title')),
                ('banner', models.URLField(blank=True, max_length=255, null=True, verbose_name='Banner URL')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Meta Description')),
                ('keywords', models.TextField(blank=True, null=True, verbose_name='Meta Keywords')),
                ('follow', models.BooleanField(default=True, verbose_name='Follow Links')),
                ('index', models.BooleanField(default=True, verbose_name='Index Page')),
                ('author', models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta Author')),
            ],
        ),
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-pub_date']},
        ),
        migrations.AddField(
            model_name='article',
            name='description',
            field=models.CharField(max_length=160, null=True, verbose_name='Short Description'),
        ),
        migrations.AddField(
            model_name='article',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Publish Date'),
        ),
        migrations.AddField(
            model_name='article',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='article',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=70, unique=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blogs.category'),
        ),
    ]
