# Generated by Django 4.0.4 on 2022-11-07 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentation', '0002_document_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='category',
        ),
        migrations.RemoveField(
            model_name='document',
            name='tags',
        ),
        migrations.DeleteModel(
            name='category',
        ),
        migrations.DeleteModel(
            name='document',
        ),
    ]
