# Generated by Django 4.0.4 on 2022-11-07 13:11

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blogs', '0007_tag_created_at'),
        ('documentation', '0003_remove_document_category_remove_document_tags_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Category Name')),
                ('slug', models.SlugField(blank=True, null=True, verbose_name='slug')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Title')),
                ('content', ckeditor.fields.RichTextField(verbose_name='Content')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('slug', models.SlugField(blank=True, null=True, verbose_name='slug')),
                ('published', models.BooleanField(default=False, verbose_name='published')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documentation.category', verbose_name='Document Category')),
                ('tags', models.ManyToManyField(blank=True, to='blogs.tag', verbose_name='Tags')),
            ],
        ),
    ]
