# Generated by Django 4.0.4 on 2022-12-13 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentation', '0006_alter_document_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='sequence',
            field=models.IntegerField(default=1, verbose_name='Sequence Number'),
            preserve_default=False,
        ),
    ]
