# Generated by Django 4.0.4 on 2022-05-05 22:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('firstname', models.CharField(max_length=100, verbose_name='First name')),
                ('lastname', models.CharField(max_length=100, verbose_name='Last name')),
                ('company_name', models.CharField(blank=True, max_length=100, verbose_name='Company name')),
                ('bracket', models.CharField(choices=[('msp', 'MSP'), ('it_department', 'IT Department'), ('other', 'Other')], default='msp', max_length=25, verbose_name='bracket')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('address', models.TextField(blank=True, verbose_name='Address')),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Contact no.')),
                ('subdomain', models.CharField(blank=True, max_length=25, verbose_name='Subdomain')),
                ('number_of_devices', models.IntegerField(verbose_name='Number of devices')),
                ('contact_mode', models.CharField(choices=[('phone', 'Phone'), ('email', 'Email')], default='email', max_length=25, verbose_name='Contact mode')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('slug', models.SlugField(blank=True, null=True, verbose_name='slug')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
