# Generated by Django 4.0.4 on 2022-12-13 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_contact_us'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contact_us',
            new_name='ContactUs',
        ),
    ]
