# Generated by Django 4.0.4 on 2023-01-06 05:58

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_rename_contact_us_contactus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Contact number'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='subdomain',
            field=models.CharField(max_length=25, verbose_name='Subdomain'),
        ),
    ]
