# Generated by Django 4.0.4 on 2024-03-03 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_alter_customer_phone_number_alter_customer_subdomain'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='user',
        ),
        migrations.AlterField(
            model_name='customer',
            name='company_name',
            field=models.CharField(max_length=100, verbose_name='Company name'),
        ),
    ]
